user:
  maximum_name: 50
  maximum_email: 255
  minimum_pass: 6
  size: 50
  expire: 2
  per_page: 7
sessions:
  remember_me: "1"
users:
  size_hp: 80
  page: 10
settings:
  port: "587"
micropost:
  maximum: 140
  size_micro: 50
  size_picture: 5
user_info:
  size_img: 50
uploaders:
  picture_upload: 400
